# Generated by Django 3.2.9 on 2021-11-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255, verbose_name='名称')),
                ('app_logo', models.CharField(max_length=255, verbose_name='图标')),
                ('app_remark', models.CharField(max_length=255, verbose_name='备注')),
                ('db_insert_time', models.DateTimeField(verbose_name='插入时间')),
                ('app_hash', models.CharField(max_length=255, verbose_name='Hash')),
                ('app_key', models.CharField(max_length=255, verbose_name='Key')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用',
                'db_table': 'bot_app',
            },
        ),
    ]
