# Generated by Django 3.2.9 on 2021-11-24 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0002_alter_app_db_insert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='db_insert_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 9, 43, 32, 496693, tzinfo=utc), verbose_name='插入时间'),
        ),
    ]
