# Generated by Django 3.2.9 on 2021-11-24 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0003_alter_app_db_insert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='db_insert_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='插入时间'),
        ),
    ]
