# Generated by Django 3.2.9 on 2021-11-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0004_alter_app_db_insert_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=255, verbose_name='名称')),
                ('robot_logo', models.CharField(max_length=255, verbose_name='图标')),
                ('robot_detail', models.CharField(max_length=255, verbose_name='描述')),
                ('robot_status', models.IntegerField(default=1, verbose_name='状态')),
                ('robot_ttl', models.IntegerField(verbose_name='闲置等待时长')),
                ('odst_threshold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='智能填槽阈值')),
                ('pos_status', models.IntegerField(default=1, verbose_name='自动添加预置回复')),
                ('pos_num', models.IntegerField(default=3, verbose_name='推荐个数')),
                ('pos_source', models.CharField(default='["popular","personal","entity"]', max_length=255, verbose_name='推荐源')),
                ('goback_action', models.IntegerField(default=1, verbose_name='是否可以回退')),
                ('exit_action', models.IntegerField(default=1, verbose_name='是否主动退出')),
                ('exit_rsp_mode', models.IntegerField(default=1, verbose_name='退出响应模式')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.app')),
            ],
            options={
                'verbose_name': '场景',
                'verbose_name_plural': '场景',
                'db_table': 'bot_robot',
            },
        ),
    ]
