# Generated by Django 3.2.9 on 2021-11-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0006_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '意图', 'verbose_name_plural': '意图'},
        ),
        migrations.AlterModelTable(
            name='task',
            table='bot_task',
        ),
    ]
