# Generated by Django 3.2.9 on 2021-11-26 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0007_auto_20211126_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255, verbose_name='名称')),
                ('entity_desc', models.CharField(max_length=255, verbose_name='entity_desc')),
                ('entity_detail', models.CharField(max_length=255, verbose_name='entity_detail')),
                ('entity_type', models.IntegerField(verbose_name='entity_type')),
            ],
            options={
                'verbose_name': '实例',
                'verbose_name_plural': '实例',
                'db_table': 'bot_entity',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('alias', models.CharField(max_length=255, verbose_name='alias')),
                ('disposable', models.BooleanField(default=False)),
                ('fill_slot_with_query', models.BooleanField(default=False)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.robot', verbose_name='关联机器人')),
                ('source_entities', models.ManyToManyField(to='app_task.Entity')),
            ],
            options={
                'verbose_name': '词槽',
                'verbose_name_plural': '词槽',
                'db_table': 'bot_slot',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='单元名称')),
                ('type_id', models.IntegerField(verbose_name='类型')),
                ('uri', models.CharField(max_length=255, verbose_name='跳转意图')),
                ('max_interval', models.IntegerField(verbose_name='尝试询问次数')),
                ('mult_val', models.IntegerField(verbose_name='机器人得到多个值时，向用户澄清')),
                ('fill_any_time', models.BooleanField(verbose_name='仅在当前单元询问时填槽')),
                ('order_id', models.IntegerField(verbose_name='未知')),
                ('rsp_mode', models.IntegerField(verbose_name='未知')),
                ('first_order', models.IntegerField(verbose_name='未知')),
                ('pre_check', models.CharField(max_length=255, verbose_name='未知')),
                ('run_once', models.BooleanField(verbose_name='运行一次')),
                ('bound_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.slot', verbose_name='关联词槽')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.task', verbose_name='关联任务（意图）')),
            ],
            options={
                'verbose_name': '响应',
                'verbose_name_plural': '响应',
                'db_table': 'bot_block',
            },
        ),
    ]
