# Generated by Django 3.2.9 on 2021-11-27 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0008_block_entity_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '单元', 'verbose_name_plural': '单元'},
        ),
        migrations.CreateModel(
            name='BlockShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut_options', models.CharField(default='', max_length=255, verbose_name='操作')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.block', verbose_name='单元')),
            ],
            options={
                'verbose_name': '预置回复',
                'verbose_name_plural': '预置回复',
                'db_table': 'bot_block_shortcut',
            },
        ),
        migrations.CreateModel(
            name='BlockResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(default='', max_length=255, verbose_name='响应规则')),
                ('rsp_once', models.BooleanField(default=False, verbose_name='响应一次')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.block', verbose_name='单元')),
            ],
            options={
                'verbose_name': '单元响应处理',
                'verbose_name_plural': '单元响应处理',
                'db_table': 'bot_block_response',
            },
        ),
        migrations.CreateModel(
            name='BlockRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(default='', max_length=255, verbose_name='条件')),
                ('value', models.CharField(default='', max_length=255, verbose_name='值')),
                ('from_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_block', to='app_task.block', verbose_name='起点')),
                ('to_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_block', to='app_task.block', verbose_name='终点')),
            ],
            options={
                'verbose_name': '单元跳转关系',
                'verbose_name_plural': '单元跳转关系',
                'db_table': 'bot_block_relation',
            },
        ),
        migrations.CreateModel(
            name='BlockDeferred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deferred_time', models.IntegerField(verbose_name='次数')),
                ('response', models.CharField(default='', max_length=255, verbose_name='操作')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.block', verbose_name='单元')),
            ],
            options={
                'verbose_name': '延期设置',
                'verbose_name_plural': '延期设置',
                'db_table': 'bot_block_deferred',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='block_relations',
            field=models.ManyToManyField(through='app_task.BlockRelation', to='app_task.Block', verbose_name='单元跳转关系'),
        ),
    ]
