# Generated by Django 3.2.9 on 2021-11-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0008_block_entity_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '单元', 'verbose_name_plural': '单元'},
        ),
        migrations.AddField(
            model_name='block',
            name='disable_exit',
            field=models.IntegerField(default=0, verbose_name='允许退出'),
        ),
        migrations.AddField(
            model_name='block',
            name='disable_goback',
            field=models.IntegerField(default=0, verbose_name='允许后退'),
        ),
    ]
