# Generated by Django 3.2.9 on 2021-11-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0010_trigger_triggerinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trigger',
            options={'verbose_name': '触发器', 'verbose_name_plural': '触发器'},
        ),
        migrations.AlterModelOptions(
            name='triggerinfo',
            options={'verbose_name': '触发器信息', 'verbose_name_plural': '触发器信息'},
        ),
        migrations.AddField(
            model_name='block',
            name='position_x',
            field=models.IntegerField(default=0, verbose_name='x坐标'),
        ),
        migrations.AddField(
            model_name='block',
            name='position_y',
            field=models.IntegerField(default=0, verbose_name='y坐标'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='position_x',
            field=models.IntegerField(default=0, verbose_name='x坐标'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='position_y',
            field=models.IntegerField(default=0, verbose_name='y坐标'),
        ),
    ]
