# Generated by Django 3.2.9 on 2021-11-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0009_auto_20211126_1503'),
        ('app_task', '0011_auto_20211127_1135'),
    ]

    operations = [
    ]
